In [27]:
%cd /Users/madhav/module-1-biomarker-data-table_seven

/Users/madhav/module-1-biomarker-data-table_seven


In [80]:
#loading in training data
import pandas as pd
training_data = pd.read_csv('data/biomarker-train.csv')

In [81]:
#loading in testing data
test_data = pd.read_csv('data/biomarker-test.csv')
test_data = test_data.drop(columns=['Target Full Name', 'ADOS        Total Score'])

In [82]:
test_data = test_data.dropna()

In [84]:
training_data.head()

Group  Target Full Name  E3 ubiquitin-protein ligase CHIP  \
0   ASD               NaN                             458.9   
1   ASD               NaN                             618.6   
2   ASD               NaN                             916.8   
3   ASD               NaN                             458.3   
4   ASD               NaN                             395.6   

   CCAAT/enhancer-binding protein beta  Gamma-enolase  \
0                               1367.2          780.8   
1                               1489.3          732.7   
2                               1716.5          877.2   
3                               1021.1         1142.3   
4                               1356.4          638.7   

   E3 SUMO-protein ligase PIAS4  Interleukin-10 receptor subunit alpha  \
0                         905.7                                 2244.0   
1                        1229.6                                 1647.0   
2                         978.6                                 1970.6   
3                         740.1                                 1669.8   
4                        1044.6                                 1821.8   

   Signal transducer and activator of transcription 3  \
0                                              450.2    
1                                              467.0    
2                                              501.0    
3                                              372.4    
4                                              326.2    

   Interferon regulatory factor 1  Transcription factor AP-1  ...  \
0                          1469.7                     3401.5  ...   
1                          1041.0                     3114.2  ...   
2                          1434.8                     3013.8  ...   
3                          1022.4                     2623.5  ...   
4                          1085.7                     2696.7  ...   

   Transgelin-2  ATP synthase subunit O, mitochondrial  Pro-opiomelanocortin  \
0        3365.9                                 1424.5                 601.4   
1        3016.2                                 2156.9                 895.7   
2        4124.4                                 1488.3                 688.7   
3        2962.8                                 1731.0                 525.3   
4        3327.2                                 1708.2                 585.0   

   Quinone oxidoreductase-like protein 1  Pigment epithelium-derived factor  \
0                                 2608.2                            24093.8   
1                                 2313.6                            24904.5   
2                                 2466.8                            24585.4   
3                                 1579.9                            30119.9   
4                                 2193.7                            23211.6   

   Cathepsin F  Formimidoyltransferase-cyclodeaminase  \
0       2600.0                                 1780.3   
1       2048.7                                 9942.4   
2       3737.1                                 2421.2   
3       2453.0                                  307.7   
4       2667.9                                 1032.4   

   Ubiquitin carboxyl-terminal hydrolase 25  Plexin-B2  \
0                                    1663.8     2629.7   
1                                    1462.6     2024.1   
2                                    1670.7     2525.2   
3                                    1444.9     1648.8   
4                                    1478.1     1853.7   

   ADOS        Total Score  
0                       22  
1                        8  
2                       22  
3                        7  
4                       21  

[5 rows x 1320 columns]

In [85]:
training_data = training_data.drop(columns=['Target Full Name', 'ADOS        Total Score'])

In [86]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

predictors = training_data.drop(columns=['Group'])
response = training_data['Group']

# Fit Random Forest
rf = RandomForestClassifier(
    n_estimators=1000,
    random_state=101422,
    oob_score=False, 
)

rf.fit(X=predictors, y=response)

#confusion matrix
y_pred = rf.predict(predictors)
conf_mat = confusion_matrix(response, y_pred)
print(conf_mat)

# Compute feature importance
importances = pd.DataFrame({
    'protein': predictors.columns,
    'MeanDecreaseGini': rf.feature_importances_
})

# Get top 10 proteins
proteins_s2 = (
    importances
    .nlargest(10, 'MeanDecreaseGini')
    ['protein']
    .tolist()
)

print(proteins_s2)

[[61  0]
 [ 0 62]]
['Dermatopontin', 'Immunoglobulin D', 'C-X-C motif chemokine 16', 'Pleiotrophin', 'Mitogen-activated protein kinase 14', 'CD166 antigen', 'Hyaluronan and proteoglycan link protein 1', 'Coagulation factor IX', 'Neurogenic locus notch homolog protein 1', 'Dickkopf-related protein 3']


In [88]:
#performance with a simple subset (top 8 proteins)
simple_proteins = list(['Dermatopontin', 'Immunoglobulin D', 'C-X-C motif chemokine 16', 'Pleiotrophin', 'Mitogen-activated protein kinase 14', 'CD166 antigen', 'Hyaluronan and proteoglycan link protein 1', 'Coagulation factor IX'])

predictors_simple = training_data[simple_proteins]
rf_simple = RandomForestClassifier(
    n_estimators=1000,
    random_state=101422,
    oob_score=False, 
)
rf_simple.fit(X=predictors_simple, y=response)

X_test_simple = test_data.drop(columns=['Group'])
X_test_simple = X_test_simple[simple_proteins]

y_test_simple = test_data['Group']

y_pred_simple = rf_simple.predict(X_test_simple)

conf_mat_simple = confusion_matrix(y_test_simple, y_pred_simple)

accuracy_simple = np.trace(conf_mat_simple) / np.sum(conf_mat_simple)
print("Accuracy:", accuracy_simple)

Accuracy: 0.8064516129032258


In [91]:
conf_mat_simple

array([[13,  2],
       [ 4, 12]])

In [92]:
conf_mat_s2

array([[12,  3],
       [ 3, 13]])